name: YACLib CI

on:
  pull_request:
    branches:
      - main

jobs:
  main:
    runs-on: ${{ matrix.config.os }}
    name: "${{matrix.config.os}} / ${{matrix.config.cxx}} / ${{matrix.build_type}}"
    strategy:
      fail-fast: false
      matrix:
        build_type: [ Debug ]
        config:
          - {
            os: ubuntu-latest,
            cc: "gcc-10", cxx: "g++-10"
          }
          - {
            os: ubuntu-latest,
            cc: "clang-12", cxx: "clang++-12"
          }
          - {
            os: windows-latest,
            cc: "cl", cxx: "cl",
          }
    steps:
      - uses: actions/checkout@v2

      - name: Configure CMake
        run: cmake
          -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
          -DCMAKE_C_COMPILER=${{ matrix.config.cc }}
          -DCMAKE_CXX_COMPILER=${{ matrix.config.cxx }}
          -DBUILD_TESTING=ON

      - name: Build
        run: cmake --build . --config ${{ matrix.build_type }}

      - name: Test
        run: ctest --output-on-failure -C ${{ matrix.build_type }}
