name: Test coverage

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  main:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ ubuntu-20.04 ]
        cc: [ gcc-10 ]
        cxx: [ g++-10 ]
        build_type: [ Debug ]
        cxx_standard: [ 17 ]

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run:
          sudo apt install ${{ matrix.cc }} ${{ matrix.cxx }} lcov

      - name: Configure CMake
        run:
          mkdir build &&
          cd build &&
          cmake ..
          -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
          -DCMAKE_C_COMPILER=${{ matrix.cc }}
          -DCMAKE_CXX_COMPILER=${{ matrix.cxx }}
          -DYACLIB_BUILD_TESTING=ON
          -DYACLIB_BUILD_EXAMPLES=ON
          -DYACLIB_COVERAGE=ON
          -DYACLIB_CXX_STANDARD=${{ matrix.cxx_standard }}

      - name: Build
        run:
          cmake --build build --config ${{ matrix.build_type }}

      - name: Test
        run:
          cd build &&
          ctest --output-on-failure -C ${{ matrix.build_type }} -V

      - name: Collect lcov info
        run:
          cd build &&
          lcov -d . -c                  -o lcov.info &&
          lcov -r lcov.info '/usr/*'    -o lcov.info &&
          lcov -r lcov.info '*/_deps/*' -o lcov.info &&
          lcov -r lcov.info '*/test/*'  -o lcov.info &&
          lcov --list lcov.info

      - name: codecov
        uses: codecov/codecov-action@v2.0.3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: build/lcov.info
